# Generated by Django 5.2.3 on 2025-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
